#.yml allows multiple properties in a single file
spring:
  datasource:
    generate-unique-name: false       #keeps the JDBC URL in h2-console as 'testdb' 
  h2:
    console:
      enabled: true
      path: /h2-console
      
